import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid min-h-screen grid-rows[60px,1fr,120px]">
        <header className="bg-blue-400 py-4">
          <div className="m-auto justify-between flex max-w-screen-md items-center">
            <h1 className="text-2xl font-semibold">
              <Link href="/">DEMO Streaming</Link>
            </h1>
            <nav className="flex items-center gap-4">
              <span>Log in</span>
              <button className="bg-slate-800 px-4 py-1 text-white">
                Start your free trial
              </button>
            </nav>
          </div>
        </header>
        <main>{children}</main>
        <footer className="bg-slate-600 py-4 text-white">
          <div className="m-auto max-w-screen-md px-4">
            Home Terms and Conditions | Privacy Policy | Collection Statemente |
            Help | Manage Account
          </div>
        </footer>
      </body>
    </html>
  );
}
